version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Exponha a porta do backend
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:Clarice@3010@db:5432/postgres?schema=public
    depends_on:
      - db
    command: sh -c "npm install && npx prisma migrate deploy && npm start"  # Execute as migrations e depois inicie o app
 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Clarice@3010
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports: 
      - "5432:5432"

volumes:
  pgdata:
